/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.Customer;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerRecord extends UpdatableRecordImpl<CustomerRecord> implements Record11<Integer, String, String, String, String, String, String, String, String, Boolean, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>purchase.customer.customer_id</code>.
     */
    public void setCustomerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>purchase.customer.customer_id</code>.
     */
    public Integer getCustomerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>purchase.customer.customer_code</code>.
     */
    public void setCustomerCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>purchase.customer.customer_code</code>.
     */
    public String getCustomerCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>purchase.customer.customer_name</code>.
     */
    public void setCustomerName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>purchase.customer.customer_name</code>.
     */
    public String getCustomerName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>purchase.customer.customer_inn</code>.
     */
    public void setCustomerInn(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>purchase.customer.customer_inn</code>.
     */
    public String getCustomerInn() {
        return (String) get(3);
    }

    /**
     * Setter for <code>purchase.customer.customer_kpp</code>.
     */
    public void setCustomerKpp(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>purchase.customer.customer_kpp</code>.
     */
    public String getCustomerKpp() {
        return (String) get(4);
    }

    /**
     * Setter for <code>purchase.customer.customer_legal_address</code>.
     */
    public void setCustomerLegalAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>purchase.customer.customer_legal_address</code>.
     */
    public String getCustomerLegalAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>purchase.customer.customer_postal_address</code>.
     */
    public void setCustomerPostalAddress(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>purchase.customer.customer_postal_address</code>.
     */
    public String getCustomerPostalAddress() {
        return (String) get(6);
    }

    /**
     * Setter for <code>purchase.customer.customer_email</code>.
     */
    public void setCustomerEmail(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>purchase.customer.customer_email</code>.
     */
    public String getCustomerEmail() {
        return (String) get(7);
    }

    /**
     * Setter for <code>purchase.customer.customer_code_main</code>.
     */
    public void setCustomerCodeMain(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>purchase.customer.customer_code_main</code>.
     */
    public String getCustomerCodeMain() {
        return (String) get(8);
    }

    /**
     * Setter for <code>purchase.customer.is_organization</code>.
     */
    public void setIsOrganization(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>purchase.customer.is_organization</code>.
     */
    public Boolean getIsOrganization() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>purchase.customer.is_person</code>.
     */
    public void setIsPerson(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>purchase.customer.is_person</code>.
     */
    public Boolean getIsPerson() {
        return (Boolean) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, String, String, String, String, String, String, String, String, Boolean, Boolean> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Integer, String, String, String, String, String, String, String, String, Boolean, Boolean> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Customer.CUSTOMER.CUSTOMER_ID;
    }

    @Override
    public Field<String> field2() {
        return Customer.CUSTOMER.CUSTOMER_CODE;
    }

    @Override
    public Field<String> field3() {
        return Customer.CUSTOMER.CUSTOMER_NAME;
    }

    @Override
    public Field<String> field4() {
        return Customer.CUSTOMER.CUSTOMER_INN;
    }

    @Override
    public Field<String> field5() {
        return Customer.CUSTOMER.CUSTOMER_KPP;
    }

    @Override
    public Field<String> field6() {
        return Customer.CUSTOMER.CUSTOMER_LEGAL_ADDRESS;
    }

    @Override
    public Field<String> field7() {
        return Customer.CUSTOMER.CUSTOMER_POSTAL_ADDRESS;
    }

    @Override
    public Field<String> field8() {
        return Customer.CUSTOMER.CUSTOMER_EMAIL;
    }

    @Override
    public Field<String> field9() {
        return Customer.CUSTOMER.CUSTOMER_CODE_MAIN;
    }

    @Override
    public Field<Boolean> field10() {
        return Customer.CUSTOMER.IS_ORGANIZATION;
    }

    @Override
    public Field<Boolean> field11() {
        return Customer.CUSTOMER.IS_PERSON;
    }

    @Override
    public Integer component1() {
        return getCustomerId();
    }

    @Override
    public String component2() {
        return getCustomerCode();
    }

    @Override
    public String component3() {
        return getCustomerName();
    }

    @Override
    public String component4() {
        return getCustomerInn();
    }

    @Override
    public String component5() {
        return getCustomerKpp();
    }

    @Override
    public String component6() {
        return getCustomerLegalAddress();
    }

    @Override
    public String component7() {
        return getCustomerPostalAddress();
    }

    @Override
    public String component8() {
        return getCustomerEmail();
    }

    @Override
    public String component9() {
        return getCustomerCodeMain();
    }

    @Override
    public Boolean component10() {
        return getIsOrganization();
    }

    @Override
    public Boolean component11() {
        return getIsPerson();
    }

    @Override
    public Integer value1() {
        return getCustomerId();
    }

    @Override
    public String value2() {
        return getCustomerCode();
    }

    @Override
    public String value3() {
        return getCustomerName();
    }

    @Override
    public String value4() {
        return getCustomerInn();
    }

    @Override
    public String value5() {
        return getCustomerKpp();
    }

    @Override
    public String value6() {
        return getCustomerLegalAddress();
    }

    @Override
    public String value7() {
        return getCustomerPostalAddress();
    }

    @Override
    public String value8() {
        return getCustomerEmail();
    }

    @Override
    public String value9() {
        return getCustomerCodeMain();
    }

    @Override
    public Boolean value10() {
        return getIsOrganization();
    }

    @Override
    public Boolean value11() {
        return getIsPerson();
    }

    @Override
    public CustomerRecord value1(Integer value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public CustomerRecord value2(String value) {
        setCustomerCode(value);
        return this;
    }

    @Override
    public CustomerRecord value3(String value) {
        setCustomerName(value);
        return this;
    }

    @Override
    public CustomerRecord value4(String value) {
        setCustomerInn(value);
        return this;
    }

    @Override
    public CustomerRecord value5(String value) {
        setCustomerKpp(value);
        return this;
    }

    @Override
    public CustomerRecord value6(String value) {
        setCustomerLegalAddress(value);
        return this;
    }

    @Override
    public CustomerRecord value7(String value) {
        setCustomerPostalAddress(value);
        return this;
    }

    @Override
    public CustomerRecord value8(String value) {
        setCustomerEmail(value);
        return this;
    }

    @Override
    public CustomerRecord value9(String value) {
        setCustomerCodeMain(value);
        return this;
    }

    @Override
    public CustomerRecord value10(Boolean value) {
        setIsOrganization(value);
        return this;
    }

    @Override
    public CustomerRecord value11(Boolean value) {
        setIsPerson(value);
        return this;
    }

    @Override
    public CustomerRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, Boolean value10, Boolean value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerRecord
     */
    public CustomerRecord() {
        super(Customer.CUSTOMER);
    }

    /**
     * Create a detached, initialised CustomerRecord
     */
    public CustomerRecord(Integer customerId, String customerCode, String customerName, String customerInn, String customerKpp, String customerLegalAddress, String customerPostalAddress, String customerEmail, String customerCodeMain, Boolean isOrganization, Boolean isPerson) {
        super(Customer.CUSTOMER);

        setCustomerId(customerId);
        setCustomerCode(customerCode);
        setCustomerName(customerName);
        setCustomerInn(customerInn);
        setCustomerKpp(customerKpp);
        setCustomerLegalAddress(customerLegalAddress);
        setCustomerPostalAddress(customerPostalAddress);
        setCustomerEmail(customerEmail);
        setCustomerCodeMain(customerCodeMain);
        setIsOrganization(isOrganization);
        setIsPerson(isPerson);
    }
}
