/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Purchase;
import jooqdata.tables.records.CustomerRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function11;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Customer extends TableImpl<CustomerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>purchase.customer</code>
     */
    public static final Customer CUSTOMER = new Customer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomerRecord> getRecordType() {
        return CustomerRecord.class;
    }

    /**
     * The column <code>purchase.customer.customer_id</code>.
     */
    public final TableField<CustomerRecord, Integer> CUSTOMER_ID = createField(DSL.name("customer_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>purchase.customer.customer_code</code>.
     */
    public final TableField<CustomerRecord, String> CUSTOMER_CODE = createField(DSL.name("customer_code"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>purchase.customer.customer_name</code>.
     */
    public final TableField<CustomerRecord, String> CUSTOMER_NAME = createField(DSL.name("customer_name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>purchase.customer.customer_inn</code>.
     */
    public final TableField<CustomerRecord, String> CUSTOMER_INN = createField(DSL.name("customer_inn"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>purchase.customer.customer_kpp</code>.
     */
    public final TableField<CustomerRecord, String> CUSTOMER_KPP = createField(DSL.name("customer_kpp"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>purchase.customer.customer_legal_address</code>.
     */
    public final TableField<CustomerRecord, String> CUSTOMER_LEGAL_ADDRESS = createField(DSL.name("customer_legal_address"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>purchase.customer.customer_postal_address</code>.
     */
    public final TableField<CustomerRecord, String> CUSTOMER_POSTAL_ADDRESS = createField(DSL.name("customer_postal_address"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>purchase.customer.customer_email</code>.
     */
    public final TableField<CustomerRecord, String> CUSTOMER_EMAIL = createField(DSL.name("customer_email"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>purchase.customer.customer_code_main</code>.
     */
    public final TableField<CustomerRecord, String> CUSTOMER_CODE_MAIN = createField(DSL.name("customer_code_main"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>purchase.customer.is_organization</code>.
     */
    public final TableField<CustomerRecord, Boolean> IS_ORGANIZATION = createField(DSL.name("is_organization"), SQLDataType.BOOLEAN.defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>purchase.customer.is_person</code>.
     */
    public final TableField<CustomerRecord, Boolean> IS_PERSON = createField(DSL.name("is_person"), SQLDataType.BOOLEAN.defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "");

    private Customer(Name alias, Table<CustomerRecord> aliased) {
        this(alias, aliased, null);
    }

    private Customer(Name alias, Table<CustomerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>purchase.customer</code> table reference
     */
    public Customer(String alias) {
        this(DSL.name(alias), CUSTOMER);
    }

    /**
     * Create an aliased <code>purchase.customer</code> table reference
     */
    public Customer(Name alias) {
        this(alias, CUSTOMER);
    }

    /**
     * Create a <code>purchase.customer</code> table reference
     */
    public Customer() {
        this(DSL.name("customer"), null);
    }

    public <O extends Record> Customer(Table<O> child, ForeignKey<O, CustomerRecord> key) {
        super(child, key, CUSTOMER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Purchase.PURCHASE;
    }

    @Override
    public Identity<CustomerRecord, Integer> getIdentity() {
        return (Identity<CustomerRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<CustomerRecord> getPrimaryKey() {
        return Keys.CUSTOMER_PKEY;
    }

    @Override
    public List<UniqueKey<CustomerRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CUSTOMER_CUSTOMER_CODE_KEY);
    }

    @Override
    public List<ForeignKey<CustomerRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CUSTOMER__FK_CUSTOMER_CODE_MAIN);
    }

    private transient Customer _customer;

    /**
     * Get the implicit join path to the <code>purchase.customer</code> table.
     */
    public Customer customer() {
        if (_customer == null)
            _customer = new Customer(this, Keys.CUSTOMER__FK_CUSTOMER_CODE_MAIN);

        return _customer;
    }

    @Override
    public Customer as(String alias) {
        return new Customer(DSL.name(alias), this);
    }

    @Override
    public Customer as(Name alias) {
        return new Customer(alias, this);
    }

    @Override
    public Customer as(Table<?> alias) {
        return new Customer(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Customer rename(String name) {
        return new Customer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Customer rename(Name name) {
        return new Customer(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Customer rename(Table<?> name) {
        return new Customer(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, String, String, String, String, String, String, String, String, Boolean, Boolean> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function11<? super Integer, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super Boolean, ? super Boolean, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function11<? super Integer, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super Boolean, ? super Boolean, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
